### PR TITLE
Potential Example 

### PR DESCRIPTION
**Pull request by cortner**
cc @zhanglw0521 @CheukHinHoJerry

### CODE REVIEW

**Comment by CheukHinHoJerry** [comment]
@zhanglw0521 I think I am done from my end - maybe you can take care some parts as we discussed?

**Comment by cortner** [comment]
I added an alternative implementation of `append_layer` named `append_layers`. It enforces giving layer names which I like to do anyhow. I find this a bit more elegant and one can append multiple layers at once.

**Comment by cortner** [comment]
```
model = append_layers(l_basis, 
                      get1 = WrappedFunction(t -> real.(t[1])), 
                      dot = LinearLayer(length(B[1]), 1) )
```

**Comment by cortner** [comment]
Unfortunately the above code doesn't work. Something is wrong with the input/output dimensions. Just creating a chain like this is fine: 
```julia 
model = Chain(; basis = l_basis, 
                get1 = WrappedFunction(t -> real.(t[1])), 
                dot = LinearLayer(length(B[1]), 1) )
```

**Comment by cortner** [comment]
`LuxCore.jl` can always be a dependency for everything. It's extremely lightweight and we need it everywhere.

**Comment by cortner** [comment]
I've now implemented forces and virials in a separate file `forces.jl`, I kept it separate only to not interfer with your changes. Feel free to incorporate this into what you are doing. Please don't yet delete `forces.jl` since I want to use it next to test out gradients w.r.t. parameters.

**Comment by cortner** [comment]
@zhanglw0521  -- some of the issues I raised over the past few hours probably shouldn't go into this PR but into a separate PR and the we rebase onto that, or merge it. Let's please not confuse too many issues into a single PR.

**Comment by cortner** [comment]
my last commit now adds an example for differentiating the total energy w.r.t. model parameters.

**Comment by cortner** [comment]
With this we can start doing parameter estimation on just energy

**Comment by zhanglw0521** [comment]
> @zhanglw0521 -- some of the issues I raised over the past few hours probably shouldn't go into this PR but into a separate PR and the we rebase onto that, or merge it. Let's please not confuse too many issues into a single PR.
> 
> General rule is one PR per issue, unless of course there is a good reason to combine them.

I wouldn't think they should go in this PR or at least they should be done in other PRs that are based on this one. My last few commits just enabled the embedding of categorical basis onto the main chain.

**Comment by cortner** [comment]
I see lot's of great activity. Let's keep in mind that we are producing an *example* here. I will start a new repository where we build the actual interatomic potential models. Let's brainstorm a name on ZuLUIP

**Comment by zhanglw0521** [comment]
@cortner @CheukHinHoJerry @YangshuaiWang  

May I merge this PR to `main` first so that some other changes can be done based on this latest version? If everyone is ok with that, I will create another PR called "New_Potential_Example" or something like that, and future updates to this PR can go into that one.

**Comment by cortner** [comment]
yes please go ahead.

**Pull request merged**
