### PR TITLE
First Prototype of this package

### PR DESCRIPTION
**Pull request by zhanglw0521**
This PR aims to create a first prototype (a lux chain actually) that maps a configuration $\{x_i\}_i$ to the corresponding $\mathcal{B}$ basis $[B^0, B^1, ..., B^L]$. 

Currently, the tests pass, but the structure is still a little bit off compared with what we want. Still working on it...

### CODE REVIEW

**Comment by zhanglw0521** [comment]
This first error looks a little bit weird to me, which seems to indicate that RepLie has not yet been registered? Or is it just something wrong with my `Project.toml`?

**Comment by zhanglw0521** [comment]
This PR seems to have (almost) all functionalities that were shown on the whiteboard yesterday. But it still cannot pass the tests owing to the above comments.

**Comment by CheukHinHoJerry** [comment]
Seems that we don’t have a registry in CI test that contains RepLieGroups.jl ?

**Comment by cortner** [comment]
Don't worry about CI yet. I'll review asap.

**Comment by cortner** [comment]
Jerry - we might have posted at the same time. You are right we need to add the correct registry.

**Comment by cortner** [comment]
Would you Kind adding the fix?

**Comment by CheukHinHoJerry** [comment]
CI test for the code runs now but it seems that incorrect version of P4ML is used?
```julia
[ Info: Tesing L = 0 O(3) equivariance
Equivariance: Error During Test at /home/runner/work/EquivariantModels.jl/EquivariantModels.jl/test/test_equivariance.jl:27
  Test threw exception
  Expression: F(X) ≈ F(QX)
  MethodError: no method matching _valtype(::Polynomials4ML.MonoBasis, ::Type{Float64})
  
  Closest candidates are:
    _valtype(::Polynomials4ML.AtomicOrbitalsRadials, ::Type{<:Real})
     @ Polynomials4ML ~/.julia/packages/Polynomials4ML/1YAOV/src/atomicorbitalsradials/atomicorbitalsradials.jl:27
    _valtype(::Polynomials4ML.OrthPolyBasis1D3T{T1}, ::Type{T2}) where {T1, T2}
     @ Polynomials4ML ~/.julia/packages/Polynomials4ML/1YAOV/src/orthopolybasis.jl:41
    _valtype(::Polynomials4ML.STO_NG, ::Type{<:Real})
     @ Polynomials4ML ~/.julia/packages/Polynomials4ML/1YAOV/src/atomicorbitalsradials/sto_ng.jl:11
    ...
```

**Comment by zhanglw0521** [comment]
> CI test for the code runs now but it seems that incorrect version of P4ML is used?

Thank you! I used P4ML@0.1.4 and Lux@0.4.58. But maybe I should adapt to the latest rather than make the code adapt to my environment.

**Comment by CheukHinHoJerry** [comment]
Thank you. And also I suggest to run the tests with julia > 1.9.2 locally since there were some issue with version less than that before.

**Comment by zhanglw0521** [comment]
I am trying to adapt this PR to the latest version of P4ML. But I am not sure whether or not there is an issue with P4ML @0.2.2: 

When I try
```julia
using Polynomials4ML: _valtype
totdeg = 4
Rn = legendre_basis(totdeg)
_valtype(Rn,Float64)
```
it works well and returns Float64, but when I try
```julia
Rn = MonoBasis(totdeg)
_valtype(Rn,Float64)
```
`_valtype` has no definition of this kind of operation.

Maybe adding 
```julia
_valtype(::MonoBasis, T::Type{<: Real}) = T
```
to P4ML would resolve this?

**Comment by CheukHinHoJerry** [comment]
Yes I think this is a bug in P4ML. I will create a PR on that side fixing this.

**Comment by cortner** [comment]
Testing with duals and hyperduals is useful but not urgent. Maybe an issue?

**Comment by CheukHinHoJerry** [comment]
bump

**Pull request merged**
